navigation
myosotisrose/ufem-project pull request #3
Opened 2020-09-26 17:27 UTC by myosotisrose

2020-09-26 19:10 UTC, sthiepaan requested changes
Please merge #2 _Pull Request_ to develop branch first and then pull the changes from there,
so we do not see the same changes in this _PR_ 😉

2020-09-26 19:10 UTC, sthiepaan commented on css/styles.css
> +.google-navigation {
I think that _"google-" prefix is not that accurate. Can we change/simplify it to `main-nav`?

2020-09-26 19:10 UTC, sthiepaan commented on css/styles.css
> +    font-family: Arial, Helvetica, sans-serif;
Unnecessary property, please remove it

2020-09-26 19:10 UTC, sthiepaan commented on css/styles.css
> +    outline: none;
We should not remove `outline` property unless we provide some other way to show users where the current focus is.

2020-09-26 19:10 UTC, sthiepaan commented on css/styles.css
> +}
This looks like a good idea but I would not recommend limit ourselef by declaring element class name to its purpose. It would be way better if we create _modifiers_ to handle that thing.
By this I mean we can have a "core" styling for buttons and then using _BEM modifiers_ we can change their look e.g.:
```css
/* Base styling for button */
.button {
  padding: 10px;
  margin: 0;
  color: var(--c-black); /* #000 */
  background-color: var(--c-none); /* transparent */
  border: 1px solid var(--c-none); /* transparent */
  font-size: var(--fs-regular); /* 16px */
  font-weight: var(--fs-bold); /* 700 */
}

/* Modifier 1 */
.button--rounded {
  border-radius: 2px;
}

/* Modifier 2 */
.button--primary {
  color: var(--c-white); /* #fff */
  background-color: var(--c-dodger); /* #4387fd */
  border-color: var(--c-dodger); /* #4387fd */
}
```
etc.

2020-09-26 19:10 UTC, sthiepaan commented on index.html
> +                    <a href="#" class="google-navigation__link">Gmail</a>
It is always nice to have some text inside `href` even if its is just a hash. What I mostly do is writing there some descriptive name so it is easy to understand what is it suppose to be e.g.: `#URL_GMAIL`
(same for lines: 17, 20)

2020-09-26 19:10 UTC, sthiepaan commented on index.html
> +                    <button type="button" class="google-navigation__button products-button">
Unnecessary `type` attribute - `type="button"` is specified by default for buttons. The exception for that is when the button is inside `<form>...</form>` - then by default it is`type="submit"` (same for line: 23, 32)

2020-09-26 19:10 UTC, sthiepaan commented on index.html
> +                        <svg viewBox="0 0 24 24" width="30px" height="30px">
It would be way better if we set the size of an icon using _CSS_ instead of `width` and `height` attributes. We can set the class for `<svg>...</svg>` tag.
```suggestion
                        <svg class="icon main-nav__icon" viewBox="0 0 24 24">
```
This way we can define core styling for `.icon` and then set/change it using `.main-nav__icon` _"element"_ or `icon--<MODIFIER_NAME>` _"modifier"_

You can read more about _block__element--modifier_ concept at [BEM - Block Element Modifier](http://getbem.com/) page

2020-09-27 12:24 UTC, myosotisrose commented on index.html
> +                        <svg viewBox="0 0 24 24" width="30px" height="30px">
done

2020-09-27 12:25 UTC, myosotisrose commented on index.html
> +                    <button type="button" class="google-navigation__button products-button">
done

2020-09-27 12:25 UTC, myosotisrose commented on index.html
> +                    <a href="#" class="google-navigation__link">Gmail</a>
done

2020-09-27 12:25 UTC, myosotisrose commented on css/styles.css
> +    font-family: Arial, Helvetica, sans-serif;
done

2020-09-27 12:25 UTC, myosotisrose commented on css/styles.css
> +.google-navigation {
yup sure, done

2020-09-27 15:04 UTC, myosotisrose commented on css/styles.css
> +}
done

2020-09-27 15:06 UTC, myosotisrose commented on css/styles.css
> +    outline: none;
done (added underline for links and darker colours for buttons (on focus))

2020-09-27 20:46 UTC, sthiepaan approved these changes
LGTM

2020-09-27 20:47 UTC, sthiepaan commented
@myosotisrose please remember to resolve conflict(s) in `css/styles.css` before merge 😉

2020-10-03 18:49 UTC, merged